//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Sharpnado.Presentation.Forms.iOS")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyDescription("Xamarin Forms custom components and renderers")]
[assembly: System.Reflection.AssemblyProduct("Sharpnado Toolkit")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2019")]
[assembly: System.Reflection.AssemblyVersion("1.3.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.3.0")]


