//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Sharpnado.Presentation.Forms.iOS")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyDescription("Xamarin Forms custom components and renderers")]
[assembly: System.Reflection.AssemblyProduct("Sharpnado Toolkit")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2019")]
[assembly: System.Reflection.AssemblyVersion("1.4.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.4.0")]


